Product:
    type: object
    config:
        description: "Product Type"
        fields:
            id:
                type: 'Int'
                description: "Product ID"
            name:
                type: 'String'
                description: "Product Name"
            price:
                type: 'Float'
                description: "Product Price"
            quantity:
                type: 'Int'
                description: "Product Quantity"
            category:
                type: 'String'
                description: "Product Category"